# Form implementation generated from reading ui file 'uitaller.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TALLERUTC(object):
    def setupUi(self, TALLERUTC):
        TALLERUTC.setObjectName("TALLERUTC")
        TALLERUTC.resize(800, 600)
        TALLERUTC.setMinimumSize(QtCore.QSize(800, 600))
        TALLERUTC.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=TALLERUTC)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_superior = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_superior.setStyleSheet("background-color: #294273;")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_menu = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_menu.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"}")
        self.btn_menu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/lista.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_menu.setIcon(icon)
        self.btn_menu.setIconSize(QtCore.QSize(35, 35))
        self.btn_menu.setFlat(True)
        self.btn_menu.setObjectName("btn_menu")
        self.horizontalLayout_2.addWidget(self.btn_menu)
        spacerItem = QtWidgets.QSpacerItem(618, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_user = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_user.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"}\n"
"")
        self.btn_user.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/persona.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_user.setIcon(icon1)
        self.btn_user.setIconSize(QtCore.QSize(35, 35))
        self.btn_user.setFlat(True)
        self.btn_user.setObjectName("btn_user")
        self.horizontalLayout_2.addWidget(self.btn_user)
        self.btn_close = QtWidgets.QPushButton(parent=self.frame_superior)
        self.btn_close.setStyleSheet("QPushButton{\n"
"background-color: none;\n"
"}\n"
"")
        self.btn_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/cerrar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_close.setIcon(icon2)
        self.btn_close.setIconSize(QtCore.QSize(35, 35))
        self.btn_close.setFlat(True)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_2.addWidget(self.btn_close)
        self.verticalLayout.addWidget(self.frame_superior)
        self.frame_inferior = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_inferior)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(parent=self.frame_inferior)
        self.frame_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_lateral = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_lateral.setMinimumSize(QtCore.QSize(200, 0))
        self.frame_lateral.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_lateral.setStyleSheet("QFrame{\n"
"background-color: #294273;\n"
"}\n"
"QPushButton{\n"
"background-color: none;\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"}\n"
"")
        self.frame_lateral.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_lateral.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_lateral.setObjectName("frame_lateral")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_lateral)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_home = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btn_home.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_home.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_home.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_home.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/pagina-de-inicio.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_home.setIcon(icon3)
        self.btn_home.setIconSize(QtCore.QSize(35, 35))
        self.btn_home.setAutoDefault(True)
        self.btn_home.setFlat(True)
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout_2.addWidget(self.btn_home)
        self.btn_mostrar = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btn_mostrar.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_mostrar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_mostrar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_mostrar.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/consulta.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_mostrar.setIcon(icon4)
        self.btn_mostrar.setIconSize(QtCore.QSize(35, 35))
        self.btn_mostrar.setAutoDefault(True)
        self.btn_mostrar.setFlat(True)
        self.btn_mostrar.setObjectName("btn_mostrar")
        self.verticalLayout_2.addWidget(self.btn_mostrar)
        self.btn_agregar = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btn_agregar.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_agregar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_agregar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_agregar.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/mas (2).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_agregar.setIcon(icon5)
        self.btn_agregar.setIconSize(QtCore.QSize(35, 35))
        self.btn_agregar.setAutoDefault(True)
        self.btn_agregar.setFlat(True)
        self.btn_agregar.setObjectName("btn_agregar")
        self.verticalLayout_2.addWidget(self.btn_agregar)
        self.btn_editar = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btn_editar.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_editar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_editar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_editar.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/boton-editar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_editar.setIcon(icon6)
        self.btn_editar.setIconSize(QtCore.QSize(35, 35))
        self.btn_editar.setAutoDefault(True)
        self.btn_editar.setFlat(True)
        self.btn_editar.setObjectName("btn_editar")
        self.verticalLayout_2.addWidget(self.btn_editar)
        self.btn_eliminar = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btn_eliminar.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_eliminar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_eliminar.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/basura.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eliminar.setIcon(icon7)
        self.btn_eliminar.setIconSize(QtCore.QSize(40, 40))
        self.btn_eliminar.setAutoDefault(True)
        self.btn_eliminar.setFlat(True)
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.verticalLayout_2.addWidget(self.btn_eliminar)
        self.btn_alumno = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btn_alumno.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_alumno.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_alumno.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_alumno.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/graduado.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_alumno.setIcon(icon8)
        self.btn_alumno.setIconSize(QtCore.QSize(35, 35))
        self.btn_alumno.setAutoDefault(True)
        self.btn_alumno.setFlat(True)
        self.btn_alumno.setObjectName("btn_alumno")
        self.verticalLayout_2.addWidget(self.btn_alumno)
        self.btn_tutoria = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btn_tutoria.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_tutoria.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_tutoria.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_tutoria.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/tutoria (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_tutoria.setIcon(icon9)
        self.btn_tutoria.setIconSize(QtCore.QSize(35, 35))
        self.btn_tutoria.setAutoDefault(True)
        self.btn_tutoria.setFlat(True)
        self.btn_tutoria.setObjectName("btn_tutoria")
        self.verticalLayout_2.addWidget(self.btn_tutoria)
        self.btn_archivo = QtWidgets.QPushButton(parent=self.frame_lateral)
        self.btn_archivo.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_archivo.setMaximumSize(QtCore.QSize(16777215, 40))
        self.btn_archivo.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_archivo.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/barra-de-menus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_archivo.setIcon(icon10)
        self.btn_archivo.setIconSize(QtCore.QSize(35, 35))
        self.btn_archivo.setAutoDefault(True)
        self.btn_archivo.setFlat(True)
        self.btn_archivo.setObjectName("btn_archivo")
        self.verticalLayout_2.addWidget(self.btn_archivo)
        spacerItem1 = QtWidgets.QSpacerItem(17, 81, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(parent=self.frame_lateral)
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../../../../../Downloads/Recurso 1@3x.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignJustify|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout_3.addWidget(self.frame_lateral)
        self.pages = QtWidgets.QStackedWidget(parent=self.frame_2)
        self.pages.setStyleSheet("")
        self.pages.setObjectName("pages")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.label_2 = QtWidgets.QLabel(parent=self.page_home)
        self.label_2.setGeometry(QtCore.QRect(18, 10, 501, 41))
        self.label_2.setStyleSheet("QLabel {\n"
"    font-size: 44px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: ; /* Color del texto */\n"
"    color: rgb(149, 191, 86);\n"
"    text-align: center; /* Alineación del texto */\n"
"}\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(parent=self.page_home)
        self.label_6.setGeometry(QtCore.QRect(30, 70, 521, 181))
        self.label_6.setStyleSheet("QLabel {\n"
"    font-size: 20px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.page_home)
        self.label_7.setGeometry(QtCore.QRect(-10, 300, 581, 221))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("../../../../../../../Downloads/5.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.page_home)
        self.label_8.setGeometry(QtCore.QRect(440, 10, 91, 101))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("../../../../../../../Downloads/Recurso 2@3x (1).png"))
        self.label_8.setScaledContents(True)
        self.label_8.setIndent(16)
        self.label_8.setObjectName("label_8")
        self.pages.addWidget(self.page_home)
        self.page_eliminar = QtWidgets.QWidget()
        self.page_eliminar.setObjectName("page_eliminar")
        self.label_5 = QtWidgets.QLabel(parent=self.page_eliminar)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 531, 51))
        self.label_5.setStyleSheet("QLabel {\n"
"    font-size: 44px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: ; /* Color del texto */\n"
"    color: rgb(149, 191, 86);\n"
"    text-align: center; /* Alineación del texto */\n"
"}\n"
"")
        self.label_5.setObjectName("label_5")
        self.btn_taller_eliminar = QtWidgets.QPushButton(parent=self.page_eliminar)
        self.btn_taller_eliminar.setGeometry(QtCore.QRect(390, 190, 111, 41))
        self.btn_taller_eliminar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(242, 125, 22); /* Color de fondo naranja */\n"
"    color: rgb(255, 255, 255); /* Color del texto blanco */\n"
"    border: none; /* Sin borde */\n"
"    border-radius: 4px; /* Borde redondeado */\n"
"    padding: 8px 16px; /* Espacio alrededor del texto */\n"
"    font-size: 14px; /* Tamaño de la fuente */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(212, 108, 15); /* Cambia el color de fondo al pasar el mouse */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(182, 91, 8); /* Cambia el color de fondo al presionar el botón */\n"
"}\n"
"")
        self.btn_taller_eliminar.setObjectName("btn_taller_eliminar")
        self.id_taller_eliminar = QtWidgets.QLineEdit(parent=self.page_eliminar)
        self.id_taller_eliminar.setGeometry(QtCore.QRect(40, 190, 321, 41))
        self.id_taller_eliminar.setObjectName("id_taller_eliminar")
        self.lbl_respuesta = QtWidgets.QLabel(parent=self.page_eliminar)
        self.lbl_respuesta.setGeometry(QtCore.QRect(50, 300, 481, 31))
        self.lbl_respuesta.setStyleSheet("QLabel {\n"
"    font-size: 20px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #F27D16 ; /* Color del texto */\n"
"}\n"
"")
        self.lbl_respuesta.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_respuesta.setObjectName("lbl_respuesta")
        self.label_10 = QtWidgets.QLabel(parent=self.page_eliminar)
        self.label_10.setGeometry(QtCore.QRect(40, 160, 501, 16))
        self.label_10.setStyleSheet("QLabel {\n"
"    font-size: 20px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_10.setObjectName("label_10")
        self.pages.addWidget(self.page_eliminar)
        self.page_alumnos = QtWidgets.QWidget()
        self.page_alumnos.setObjectName("page_alumnos")
        self.label_23 = QtWidgets.QLabel(parent=self.page_alumnos)
        self.label_23.setGeometry(QtCore.QRect(30, 10, 521, 51))
        self.label_23.setStyleSheet("QLabel {\n"
"    font-size: 44px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: ; /* Color del texto */\n"
"    color: rgb(149, 191, 86);\n"
"    text-align: center; /* Alineación del texto */\n"
"}\n"
"")
        self.label_23.setObjectName("label_23")
        self.tb_alumno = QtWidgets.QTableWidget(parent=self.page_alumnos)
        self.tb_alumno.setGeometry(QtCore.QRect(10, 130, 551, 141))
        self.tb_alumno.setStyleSheet("QTableWidget {\n"
"    background-color: #fff;\n"
"    alternate-background-color: #f5f5f5; /* Color de fondo alternativo para filas alternas */\n"
"    border: 1px solid #ccc; /* Borde del widget */\n"
"    border-radius: 4px; /* Borde redondeado */\n"
"    gridline-color: #ccc; /* Color de las líneas de la cuadrícula */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 10px; /* Espaciado dentro de las celdas */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* Color de fondo del encabezado */\n"
"    color: #333; /* Color del texto del encabezado */\n"
"    padding: 5px; /* Espaciado dentro del encabezado */\n"
"    border: none; /* Sin borde */\n"
"    border-bottom: 1px solid #ccc; /* Borde inferior */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #e0e0e0; /* Color de fondo de la celda seleccionada */\n"
"    color: #000; /* Color del texto de la celda seleccionada */\n"
"}\n"
"")
        self.tb_alumno.setObjectName("tb_alumno")
        self.tb_alumno.setColumnCount(4)
        self.tb_alumno.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_alumno.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_alumno.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_alumno.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_alumno.setHorizontalHeaderItem(3, item)
        self.tb_alumno.horizontalHeader().setCascadingSectionResizes(False)
        self.tb_alumno.horizontalHeader().setDefaultSectionSize(137)
        self.id_alumno_buscar = QtWidgets.QLineEdit(parent=self.page_alumnos)
        self.id_alumno_buscar.setGeometry(QtCore.QRect(90, 80, 321, 41))
        self.id_alumno_buscar.setObjectName("id_alumno_buscar")
        self.btn_alumno_buscar = QtWidgets.QPushButton(parent=self.page_alumnos)
        self.btn_alumno_buscar.setGeometry(QtCore.QRect(420, 80, 111, 41))
        self.btn_alumno_buscar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(242, 125, 22); /* Color de fondo naranja */\n"
"    color: rgb(255, 255, 255); /* Color del texto blanco */\n"
"    border: none; /* Sin borde */\n"
"    border-radius: 4px; /* Borde redondeado */\n"
"    padding: 8px 16px; /* Espacio alrededor del texto */\n"
"    font-size: 14px; /* Tamaño de la fuente */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(212, 108, 15); /* Cambia el color de fondo al pasar el mouse */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(182, 91, 8); /* Cambia el color de fondo al presionar el botón */\n"
"}\n"
"")
        self.btn_alumno_buscar.setObjectName("btn_alumno_buscar")
        self.label_24 = QtWidgets.QLabel(parent=self.page_alumnos)
        self.label_24.setGeometry(QtCore.QRect(30, 90, 51, 16))
        self.label_24.setStyleSheet("QLabel {\n"
"    font-size: 20px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_24.setObjectName("label_24")
        self.tb_alumno_taller = QtWidgets.QTableWidget(parent=self.page_alumnos)
        self.tb_alumno_taller.setGeometry(QtCore.QRect(10, 360, 551, 141))
        self.tb_alumno_taller.setStyleSheet("QTableWidget {\n"
"    background-color: #fff;\n"
"    alternate-background-color: #f5f5f5; /* Color de fondo alternativo para filas alternas */\n"
"    border: 1px solid #ccc; /* Borde del widget */\n"
"    border-radius: 4px; /* Borde redondeado */\n"
"    gridline-color: #ccc; /* Color de las líneas de la cuadrícula */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 10px; /* Espaciado dentro de las celdas */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* Color de fondo del encabezado */\n"
"    color: #333; /* Color del texto del encabezado */\n"
"    padding: 5px; /* Espaciado dentro del encabezado */\n"
"    border: none; /* Sin borde */\n"
"    border-bottom: 1px solid #ccc; /* Borde inferior */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #e0e0e0; /* Color de fondo de la celda seleccionada */\n"
"    color: #000; /* Color del texto de la celda seleccionada */\n"
"}\n"
"")
        self.tb_alumno_taller.setObjectName("tb_alumno_taller")
        self.tb_alumno_taller.setColumnCount(2)
        self.tb_alumno_taller.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_alumno_taller.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_alumno_taller.setHorizontalHeaderItem(1, item)
        self.tb_alumno_taller.horizontalHeader().setCascadingSectionResizes(False)
        self.tb_alumno_taller.horizontalHeader().setDefaultSectionSize(274)
        self.label_25 = QtWidgets.QLabel(parent=self.page_alumnos)
        self.label_25.setGeometry(QtCore.QRect(10, 310, 251, 16))
        self.label_25.setStyleSheet("QLabel {\n"
"    font-size: 20px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_25.setObjectName("label_25")
        self.btn_alumno_buscar_2 = QtWidgets.QPushButton(parent=self.page_alumnos)
        self.btn_alumno_buscar_2.setGeometry(QtCore.QRect(440, 300, 111, 41))
        self.btn_alumno_buscar_2.setStyleSheet("QPushButton{\n"
"    background-color: rgb(242, 125, 22); /* Color de fondo naranja */\n"
"    color: rgb(255, 255, 255); /* Color del texto blanco */\n"
"    border: none; /* Sin borde */\n"
"    border-radius: 4px; /* Borde redondeado */\n"
"    padding: 8px 16px; /* Espacio alrededor del texto */\n"
"    font-size: 14px; /* Tamaño de la fuente */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(212, 108, 15); /* Cambia el color de fondo al pasar el mouse */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(182, 91, 8); /* Cambia el color de fondo al presionar el botón */\n"
"}\n"
"")
        self.btn_alumno_buscar_2.setObjectName("btn_alumno_buscar_2")
        self.lista_taller = QtWidgets.QListWidget(parent=self.page_alumnos)
        self.lista_taller.setGeometry(QtCore.QRect(240, 310, 171, 21))
        self.lista_taller.setObjectName("lista_taller")
        self.pages.addWidget(self.page_alumnos)
        self.page_login = QtWidgets.QWidget()
        self.page_login.setObjectName("page_login")
        self.label_9 = QtWidgets.QLabel(parent=self.page_login)
        self.label_9.setGeometry(QtCore.QRect(230, 0, 151, 51))
        self.label_9.setStyleSheet("QLabel {\n"
"    font-size: 44px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: ; /* Color del texto */\n"
"    color: rgb(149, 191, 86);\n"
"    text-align: center; /* Alineación del texto */\n"
"}\n"
"")
        self.label_9.setObjectName("label_9")
        self.frame = QtWidgets.QFrame(parent=self.page_login)
        self.frame.setGeometry(QtCore.QRect(120, 50, 341, 461))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #294273, stop:1 #ffffff);\n"
"border-radius: 50px 50px 0px 0px;\n"
"\n"
"}\n"
"QLabel {\n"
"backgorund-color: none;\n"
"}\n"
"QLineEdit {\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    background-color: NONE;\n"
"}\n"
"\n"
"QLineEdit:hover, QLineEdit:focus {\n"
"    border: 1px solid #00bfff;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"    border: 2px solid transparent;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    background-color: #ffa500;\n"
"}\n"
"\n"
"QPushButton#registerButton {\n"
"    background-color: #ff4500;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: #adff2f;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff6347;\n"
"}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.btn_ingresar = QtWidgets.QPushButton(parent=self.frame)
        self.btn_ingresar.setGeometry(QtCore.QRect(120, 360, 111, 41))
        self.btn_ingresar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(242, 125, 22); /* Color de fondo naranja */\n"
"    color: rgb(255, 255, 255); /* Color del texto blanco */\n"
"    border: none; /* Sin borde */\n"
"    border-radius: 4px; /* Borde redondeado */\n"
"    padding: 8px 16px; /* Espacio alrededor del texto */\n"
"    font-size: 14px; /* Tamaño de la fuente */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(212, 108, 15); /* Cambia el color de fondo al pasar el mouse */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(182, 91, 8); /* Cambia el color de fondo al presionar el botón */\n"
"}\n"
"")
        self.btn_ingresar.setObjectName("btn_ingresar")
        self.btn_ir_registrar = QtWidgets.QPushButton(parent=self.frame)
        self.btn_ir_registrar.setGeometry(QtCore.QRect(120, 410, 111, 41))
        self.btn_ir_registrar.setStyleSheet("QPushButton{\n"
"    background-color: none; /* Color de fondo naranja */\n"
"    color: rgb(242, 125, 22); /* Color del texto blanco */\n"
"    border: 3px solid rgb(242, 125, 22); /* Sin borde */\n"
"    border-radius: 4px; /* Borde redondeado */\n"
"    padding: 8px 16px; /* Espacio alrededor del texto */\n"
"    font-size: 14px; /* Tamaño de la fuente */\n"
"     font-weight: bold\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(242, 125, 22); /* Cambia el color de fondo al pasar el mouse */\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(182, 91, 8); /* Cambia el color de fondo al presionar el botón */\n"
"    color: #fff;\n"
"}\n"
"")
        self.btn_ir_registrar.setObjectName("btn_ir_registrar")
        self.frame_3 = QtWidgets.QFrame(parent=self.frame)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 321, 341))
        self.frame_3.setStyleSheet("QFrame {\n"
"    background-color: rgba(255, 255, 255, 127); /* 127 es aproximadamente 50% de opacidad */\n"
"border-radius: 40px 40px 0px 0px;\n"
"\n"
"}\n"
"QLabel {\n"
"backgorund-color: none;\n"
"}\n"
"QLineEdit {\n"
"    border: 1px solid #a9a9a9;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    background-color: NONE;\n"
"}\n"
"\n"
"QLineEdit:hover, QLineEdit:focus {\n"
"    border: 1px solid #00bfff;\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"    border: 2px solid transparent;\n"
"    border-radius: 4px;\n"
"    padding: 5px;\n"
"    background-color: #ffa500;\n"
"}\n"
"\n"
"QPushButton#registerButton {\n"
"    background-color: #ff4500;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: #adff2f;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #ff6347;\n"
"}\n"
"\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.usuario_login = QtWidgets.QLineEdit(parent=self.frame_3)
        self.usuario_login.setGeometry(QtCore.QRect(10, 210, 301, 31))
        self.usuario_login.setObjectName("usuario_login")
        self.contrasena_login = QtWidgets.QLineEdit(parent=self.frame_3)
        self.contrasena_login.setGeometry(QtCore.QRect(10, 270, 301, 31))
        self.contrasena_login.setObjectName("contrasena_login")
        self.label_26 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_26.setGeometry(QtCore.QRect(20, 190, 211, 16))
        self.label_26.setStyleSheet("QLabel {\n"
"    background-color: none;\n"
"    font-size: 12px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_27.setGeometry(QtCore.QRect(20, 250, 211, 16))
        self.label_27.setStyleSheet("QLabel {\n"
"    background-color: none;\n"
"    font-size: 12px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_28.setGeometry(QtCore.QRect(60, 310, 211, 16))
        self.label_28.setStyleSheet("QLabel {\n"
"    background-color: none;\n"
"    font-size: 12px; /* Tamaño de la fuente */\n"
"\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_28.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_29.setGeometry(QtCore.QRect(100, 10, 121, 151))
        self.label_29.setStyleSheet("background-color: none;")
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("../../../../../../../Downloads/Recurso 2@3x (1).png"))
        self.label_29.setScaledContents(True)
        self.label_29.setIndent(16)
        self.label_29.setObjectName("label_29")
        self.pages.addWidget(self.page_login)
        self.page_compus = QtWidgets.QWidget()
        self.page_compus.setObjectName("page_compus")
        self.label_35 = QtWidgets.QLabel(parent=self.page_compus)
        self.label_35.setGeometry(QtCore.QRect(80, 100, 49, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(parent=self.page_compus)
        self.label_36.setGeometry(QtCore.QRect(370, 100, 49, 16))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(parent=self.page_compus)
        self.label_37.setGeometry(QtCore.QRect(230, 100, 49, 16))
        self.label_37.setObjectName("label_37")
        self.status1 = QtWidgets.QLabel(parent=self.page_compus)
        self.status1.setGeometry(QtCore.QRect(80, 140, 49, 16))
        self.status1.setObjectName("status1")
        self.status2 = QtWidgets.QLabel(parent=self.page_compus)
        self.status2.setGeometry(QtCore.QRect(240, 140, 49, 16))
        self.status2.setObjectName("status2")
        self.status3 = QtWidgets.QLabel(parent=self.page_compus)
        self.status3.setGeometry(QtCore.QRect(380, 140, 49, 16))
        self.status3.setObjectName("status3")
        self.btnOcupar1 = QtWidgets.QPushButton(parent=self.page_compus)
        self.btnOcupar1.setGeometry(QtCore.QRect(60, 200, 75, 24))
        self.btnOcupar1.setObjectName("btnOcupar1")
        self.btnOcupar2 = QtWidgets.QPushButton(parent=self.page_compus)
        self.btnOcupar2.setGeometry(QtCore.QRect(220, 190, 75, 24))
        self.btnOcupar2.setObjectName("btnOcupar2")
        self.btnOcupar3 = QtWidgets.QPushButton(parent=self.page_compus)
        self.btnOcupar3.setGeometry(QtCore.QRect(360, 190, 75, 24))
        self.btnOcupar3.setObjectName("btnOcupar3")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.page_compus)
        self.lineEdit.setGeometry(QtCore.QRect(50, 300, 411, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.listView = QtWidgets.QListView(parent=self.page_compus)
        self.listView.setGeometry(QtCore.QRect(50, 340, 411, 101))
        self.listView.setObjectName("listView")
        self.pages.addWidget(self.page_compus)
        self.page_opciones_menu = QtWidgets.QWidget()
        self.page_opciones_menu.setObjectName("page_opciones_menu")
        self.btn_bebida = QtWidgets.QPushButton(parent=self.page_opciones_menu)
        self.btn_bebida.setGeometry(QtCore.QRect(30, 80, 521, 61))
        self.btn_bebida.setStyleSheet("background-color: rgb(255, 147, 24);")
        self.btn_bebida.setObjectName("btn_bebida")
        self.btn_alimento = QtWidgets.QPushButton(parent=self.page_opciones_menu)
        self.btn_alimento.setGeometry(QtCore.QRect(30, 220, 521, 61))
        self.btn_alimento.setStyleSheet("background-color: rgb(255, 147, 24);")
        self.btn_alimento.setObjectName("btn_alimento")
        self.btn_postre = QtWidgets.QPushButton(parent=self.page_opciones_menu)
        self.btn_postre.setGeometry(QtCore.QRect(30, 370, 521, 61))
        self.btn_postre.setStyleSheet("background-color: rgb(255, 147, 24);")
        self.btn_postre.setObjectName("btn_postre")
        self.label_30 = QtWidgets.QLabel(parent=self.page_opciones_menu)
        self.label_30.setGeometry(QtCore.QRect(80, 10, 411, 51))
        self.label_30.setStyleSheet("QLabel {\n"
"    font-size: 44px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: ; /* Color del texto */\n"
"    color: rgb(149, 191, 86);\n"
"    text-align: center; /* Alineación del texto */\n"
"}\n"
"")
        self.label_30.setObjectName("label_30")
        self.pages.addWidget(self.page_opciones_menu)
        self.page_bebidas = QtWidgets.QWidget()
        self.page_bebidas.setObjectName("page_bebidas")
        self.label_31 = QtWidgets.QLabel(parent=self.page_bebidas)
        self.label_31.setGeometry(QtCore.QRect(190, 20, 211, 51))
        self.label_31.setStyleSheet("QLabel {\n"
"    font-size: 44px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: ; /* Color del texto */\n"
"    color: rgb(149, 191, 86);\n"
"    text-align: center; /* Alineación del texto */\n"
"}\n"
"")
        self.label_31.setObjectName("label_31")
        self.listWidget_2 = QtWidgets.QListWidget(parent=self.page_bebidas)
        self.listWidget_2.setGeometry(QtCore.QRect(20, 120, 531, 361))
        self.listWidget_2.setStyleSheet("QListWidget#listWidget::item {\n"
"    background-color: #fff; /* Color de fondo de cada elemento */\n"
"    border-bottom: 1px solid #ccc; /* Borde inferior de cada elemento */\n"
"    padding: 10px; /* Espaciado interno de cada elemento */\n"
"}\n"
"\n"
"QListWidget#listWidget::item:selected {\n"
"    background-color: #e0e0e0; /* Color de fondo del elemento seleccionado */\n"
"}\n"
"\n"
"QListWidget#listWidget::item:hover {\n"
"    background-color: #f5f5f5; /* Color de fondo cuando se pasa el mouse sobre el elemento */\n"
"}\n"
"\n"
"QListWidget#listWidget QPushButton {\n"
"    background-color: #007bff; /* Color de fondo del botón */\n"
"    color: #fff; /* Color del texto del botón */\n"
"    border: none; /* Sin borde */\n"
"    padding: 5px 10px; /* Espaciado interno del botón */\n"
"}\n"
"\n"
"QListWidget#listWidget QPushButton:hover {\n"
"    background-color: #0056b3; /* Color de fondo del botón cuando se pasa el mouse sobre él */\n"
"}\n"
"\n"
"QListWidget#listWidget QListWidgetItem {\n"
"    min-height: 70px; /* Altura mínima de cada elemento */\n"
"}\n"
"\n"
"QListWidget#listWidget QListWidgetItem QLabel {\n"
"    margin-right: 10px; /* Margen derecho para separar el icono del texto */\n"
"}\n"
"\n"
"QListWidget#listWidget QListWidgetItem QLabel::icon {\n"
"    width: 60px; /* Ancho del icono */\n"
"    height: 60px; /* Altura del icono */\n"
"}\n"
"")
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/HAM.jpeg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item.setIcon(icon11)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/TORTA.jpeg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        item.setIcon(icon12)
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.pages.addWidget(self.page_bebidas)
        self.page_archivos = QtWidgets.QWidget()
        self.page_archivos.setObjectName("page_archivos")
        self.label_32 = QtWidgets.QLabel(parent=self.page_archivos)
        self.label_32.setGeometry(QtCore.QRect(180, 30, 251, 51))
        self.label_32.setStyleSheet("QLabel {\n"
"    font-size: 44px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: ; /* Color del texto */\n"
"    color: rgb(149, 191, 86);\n"
"    text-align: center; /* Alineación del texto */\n"
"}\n"
"")
        self.label_32.setObjectName("label_32")
        self.btn_abrir_archivo = QtWidgets.QPushButton(parent=self.page_archivos)
        self.btn_abrir_archivo.setGeometry(QtCore.QRect(370, 200, 75, 61))
        self.btn_abrir_archivo.setText("")
        self.btn_abrir_archivo.setIcon(icon10)
        self.btn_abrir_archivo.setIconSize(QtCore.QSize(50, 50))
        self.btn_abrir_archivo.setObjectName("btn_abrir_archivo")
        self.label_33 = QtWidgets.QLabel(parent=self.page_archivos)
        self.label_33.setGeometry(QtCore.QRect(150, 120, 291, 51))
        self.label_33.setStyleSheet("QLabel {\n"
"    font-size: 44px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: ; /* Color del texto */\n"
"    color: rgb(149, 191, 86);\n"
"    text-align: center; /* Alineación del texto */\n"
"}\n"
"")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(parent=self.page_archivos)
        self.label_34.setGeometry(QtCore.QRect(80, 280, 441, 51))
        self.label_34.setStyleSheet("QLabel {\n"
"    font-size: 44px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: ; /* Color del texto */\n"
"    color: rgb(149, 191, 86);\n"
"    text-align: center; /* Alineación del texto */\n"
"}\n"
"")
        self.label_34.setObjectName("label_34")
        self.nombre_archivo = QtWidgets.QLabel(parent=self.page_archivos)
        self.nombre_archivo.setGeometry(QtCore.QRect(150, 370, 171, 16))
        self.nombre_archivo.setObjectName("nombre_archivo")
        self.btn_buscar_archivo = QtWidgets.QPushButton(parent=self.page_archivos)
        self.btn_buscar_archivo.setGeometry(QtCore.QRect(380, 360, 75, 61))
        self.btn_buscar_archivo.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/lupa.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_buscar_archivo.setIcon(icon13)
        self.btn_buscar_archivo.setIconSize(QtCore.QSize(50, 50))
        self.btn_buscar_archivo.setObjectName("btn_buscar_archivo")
        self.btn_descargar_archivo = QtWidgets.QPushButton(parent=self.page_archivos)
        self.btn_descargar_archivo.setGeometry(QtCore.QRect(380, 440, 75, 61))
        self.btn_descargar_archivo.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("../../../../../../../Downloads/flecha-derecha.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_descargar_archivo.setIcon(icon14)
        self.btn_descargar_archivo.setIconSize(QtCore.QSize(50, 50))
        self.btn_descargar_archivo.setObjectName("btn_descargar_archivo")
        self.btn_abrir_explorador = QtWidgets.QPushButton(parent=self.page_archivos)
        self.btn_abrir_explorador.setGeometry(QtCore.QRect(150, 200, 75, 61))
        self.btn_abrir_explorador.setText("")
        self.btn_abrir_explorador.setIcon(icon5)
        self.btn_abrir_explorador.setIconSize(QtCore.QSize(50, 50))
        self.btn_abrir_explorador.setObjectName("btn_abrir_explorador")
        self.nombre_archivo_abrir = QtWidgets.QLabel(parent=self.page_archivos)
        self.nombre_archivo_abrir.setGeometry(QtCore.QRect(230, 180, 171, 16))
        self.nombre_archivo_abrir.setObjectName("nombre_archivo_abrir")
        self.pages.addWidget(self.page_archivos)
        self.page_editar = QtWidgets.QWidget()
        self.page_editar.setObjectName("page_editar")
        self.label_16 = QtWidgets.QLabel(parent=self.page_editar)
        self.label_16.setGeometry(QtCore.QRect(20, 10, 521, 51))
        self.label_16.setStyleSheet("QLabel {\n"
"    font-size: 44px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: ; /* Color del texto */\n"
"    color: rgb(149, 191, 86);\n"
"    text-align: center; /* Alineación del texto */\n"
"}\n"
"")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.page_editar)
        self.label_17.setGeometry(QtCore.QRect(20, 90, 461, 16))
        self.label_17.setStyleSheet("QLabel {\n"
"    font-size: 20px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_17.setObjectName("label_17")
        self.btn_taller_editar = QtWidgets.QPushButton(parent=self.page_editar)
        self.btn_taller_editar.setGeometry(QtCore.QRect(230, 460, 121, 41))
        self.btn_taller_editar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(242, 125, 22); /* Color de fondo naranja */\n"
"    color: rgb(255, 255, 255); /* Color del texto blanco */\n"
"    border: none; /* Sin borde */\n"
"    border-radius: 4px; /* Borde redondeado */\n"
"    padding: 8px 16px; /* Espacio alrededor del texto */\n"
"    font-size: 14px; /* Tamaño de la fuente */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(212, 108, 15); /* Cambia el color de fondo al pasar el mouse */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(182, 91, 8); /* Cambia el color de fondo al presionar el botón */\n"
"}\n"
"")
        self.btn_taller_editar.setObjectName("btn_taller_editar")
        self.label_18 = QtWidgets.QLabel(parent=self.page_editar)
        self.label_18.setGeometry(QtCore.QRect(40, 140, 151, 16))
        self.label_18.setStyleSheet("QLabel {\n"
"    font-size: 20px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_18.setObjectName("label_18")
        self.btn_taller_buscar = QtWidgets.QPushButton(parent=self.page_editar)
        self.btn_taller_buscar.setGeometry(QtCore.QRect(410, 130, 121, 41))
        self.btn_taller_buscar.setStyleSheet("QPushButton{\n"
"    background-color: none; /* Color de fondo naranja */\n"
"    color: rgb(242, 125, 22); /* Color del texto blanco */\n"
"    border: 3px solid rgb(242, 125, 22); /* Sin borde */\n"
"    border-radius: 4px; /* Borde redondeado */\n"
"    padding: 8px 16px; /* Espacio alrededor del texto */\n"
"    font-size: 14px; /* Tamaño de la fuente */\n"
"     font-weight: bold\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(242, 125, 22); /* Cambia el color de fondo al pasar el mouse */\n"
"    color: #fff;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(182, 91, 8); /* Cambia el color de fondo al presionar el botón */\n"
"    color: #fff;\n"
"}\n"
"")
        self.btn_taller_buscar.setObjectName("btn_taller_buscar")
        self.id_taller_editar = QtWidgets.QLineEdit(parent=self.page_editar)
        self.id_taller_editar.setGeometry(QtCore.QRect(80, 130, 321, 41))
        self.id_taller_editar.setObjectName("id_taller_editar")
        self.nombre_editar = QtWidgets.QLineEdit(parent=self.page_editar)
        self.nombre_editar.setGeometry(QtCore.QRect(230, 200, 301, 31))
        self.nombre_editar.setObjectName("nombre_editar")
        self.descripcion_editar = QtWidgets.QLineEdit(parent=self.page_editar)
        self.descripcion_editar.setGeometry(QtCore.QRect(230, 250, 301, 31))
        self.descripcion_editar.setObjectName("descripcion_editar")
        self.instructor_editar = QtWidgets.QLineEdit(parent=self.page_editar)
        self.instructor_editar.setGeometry(QtCore.QRect(230, 300, 301, 31))
        self.instructor_editar.setObjectName("instructor_editar")
        self.horario_editar = QtWidgets.QLineEdit(parent=self.page_editar)
        self.horario_editar.setGeometry(QtCore.QRect(230, 350, 301, 31))
        self.horario_editar.setObjectName("horario_editar")
        self.label_19 = QtWidgets.QLabel(parent=self.page_editar)
        self.label_19.setGeometry(QtCore.QRect(40, 210, 151, 16))
        self.label_19.setStyleSheet("QLabel {\n"
"    font-size: 20px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.page_editar)
        self.label_20.setGeometry(QtCore.QRect(40, 260, 151, 16))
        self.label_20.setStyleSheet("QLabel {\n"
"    font-size: 20px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(parent=self.page_editar)
        self.label_21.setGeometry(QtCore.QRect(40, 310, 151, 16))
        self.label_21.setStyleSheet("QLabel {\n"
"    font-size: 20px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(parent=self.page_editar)
        self.label_22.setGeometry(QtCore.QRect(40, 360, 151, 16))
        self.label_22.setStyleSheet("QLabel {\n"
"    font-size: 20px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_22.setObjectName("label_22")
        self.pages.addWidget(self.page_editar)
        self.page_agregar = QtWidgets.QWidget()
        self.page_agregar.setObjectName("page_agregar")
        self.label_4 = QtWidgets.QLabel(parent=self.page_agregar)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 521, 51))
        self.label_4.setStyleSheet("QLabel {\n"
"    font-size: 44px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: ; /* Color del texto */\n"
"    color: rgb(149, 191, 86);\n"
"    text-align: center; /* Alineación del texto */\n"
"}\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_11 = QtWidgets.QLabel(parent=self.page_agregar)
        self.label_11.setGeometry(QtCore.QRect(20, 110, 461, 16))
        self.label_11.setStyleSheet("QLabel {\n"
"    font-size: 20px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_11.setObjectName("label_11")
        self.nombre_agregar = QtWidgets.QLineEdit(parent=self.page_agregar)
        self.nombre_agregar.setGeometry(QtCore.QRect(240, 150, 301, 31))
        self.nombre_agregar.setObjectName("nombre_agregar")
        self.btn_guardar = QtWidgets.QPushButton(parent=self.page_agregar)
        self.btn_guardar.setGeometry(QtCore.QRect(230, 420, 121, 41))
        self.btn_guardar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(242, 125, 22); /* Color de fondo naranja */\n"
"    color: rgb(255, 255, 255); /* Color del texto blanco */\n"
"    border: none; /* Sin borde */\n"
"    border-radius: 4px; /* Borde redondeado */\n"
"    padding: 8px 16px; /* Espacio alrededor del texto */\n"
"    font-size: 14px; /* Tamaño de la fuente */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(212, 108, 15); /* Cambia el color de fondo al pasar el mouse */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(182, 91, 8); /* Cambia el color de fondo al presionar el botón */\n"
"}\n"
"")
        self.btn_guardar.setObjectName("btn_guardar")
        self.descripcion_agregar = QtWidgets.QLineEdit(parent=self.page_agregar)
        self.descripcion_agregar.setGeometry(QtCore.QRect(240, 200, 301, 31))
        self.descripcion_agregar.setObjectName("descripcion_agregar")
        self.instructor_agregar = QtWidgets.QLineEdit(parent=self.page_agregar)
        self.instructor_agregar.setGeometry(QtCore.QRect(240, 250, 301, 31))
        self.instructor_agregar.setObjectName("instructor_agregar")
        self.horario_agregar = QtWidgets.QLineEdit(parent=self.page_agregar)
        self.horario_agregar.setGeometry(QtCore.QRect(240, 300, 301, 31))
        self.horario_agregar.setObjectName("horario_agregar")
        self.label_12 = QtWidgets.QLabel(parent=self.page_agregar)
        self.label_12.setGeometry(QtCore.QRect(20, 160, 151, 16))
        self.label_12.setStyleSheet("QLabel {\n"
"    font-size: 20px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.page_agregar)
        self.label_13.setGeometry(QtCore.QRect(20, 210, 151, 16))
        self.label_13.setStyleSheet("QLabel {\n"
"    font-size: 20px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.page_agregar)
        self.label_14.setGeometry(QtCore.QRect(20, 260, 151, 16))
        self.label_14.setStyleSheet("QLabel {\n"
"    font-size: 20px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.page_agregar)
        self.label_15.setGeometry(QtCore.QRect(20, 310, 151, 16))
        self.label_15.setStyleSheet("QLabel {\n"
"    font-size: 20px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: #294273 ; /* Color del texto */\n"
"}\n"
"")
        self.label_15.setObjectName("label_15")
        self.pages.addWidget(self.page_agregar)
        self.page_mostrar = QtWidgets.QWidget()
        self.page_mostrar.setObjectName("page_mostrar")
        self.label_3 = QtWidgets.QLabel(parent=self.page_mostrar)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 511, 51))
        self.label_3.setStyleSheet("QLabel {\n"
"    font-size: 44px; /* Tamaño de la fuente */\n"
"    font-weight: bold; /* Negrita */\n"
"    color: ; /* Color del texto */\n"
"    color: rgb(149, 191, 86);\n"
"    text-align: center; /* Alineación del texto */\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.tb_taller = QtWidgets.QTableWidget(parent=self.page_mostrar)
        self.tb_taller.setGeometry(QtCore.QRect(10, 80, 551, 441))
        self.tb_taller.setStyleSheet("QTableWidget {\n"
"    background-color: #fff;\n"
"    alternate-background-color: #f5f5f5; /* Color de fondo alternativo para filas alternas */\n"
"    border: 1px solid #ccc; /* Borde del widget */\n"
"    border-radius: 4px; /* Borde redondeado */\n"
"    gridline-color: #ccc; /* Color de las líneas de la cuadrícula */\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 10px; /* Espaciado dentro de las celdas */\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: #f0f0f0; /* Color de fondo del encabezado */\n"
"    color: #333; /* Color del texto del encabezado */\n"
"    padding: 5px; /* Espaciado dentro del encabezado */\n"
"    border: none; /* Sin borde */\n"
"    border-bottom: 1px solid #ccc; /* Borde inferior */\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #e0e0e0; /* Color de fondo de la celda seleccionada */\n"
"    color: #000; /* Color del texto de la celda seleccionada */\n"
"}\n"
"")
        self.tb_taller.setObjectName("tb_taller")
        self.tb_taller.setColumnCount(5)
        self.tb_taller.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tb_taller.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_taller.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_taller.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_taller.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tb_taller.setHorizontalHeaderItem(4, item)
        self.tb_taller.horizontalHeader().setDefaultSectionSize(110)
        self.btn_refrescar = QtWidgets.QPushButton(parent=self.page_mostrar)
        self.btn_refrescar.setGeometry(QtCore.QRect(390, 20, 131, 41))
        self.btn_refrescar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(242, 125, 22); /* Color de fondo naranja */\n"
"    color: rgb(255, 255, 255); /* Color del texto blanco */\n"
"    border: none; /* Sin borde */\n"
"    border-radius: 4px; /* Borde redondeado */\n"
"    padding: 8px 16px; /* Espacio alrededor del texto */\n"
"    font-size: 14px; /* Tamaño de la fuente */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(212, 108, 15); /* Cambia el color de fondo al pasar el mouse */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(182, 91, 8); /* Cambia el color de fondo al presionar el botón */\n"
"}\n"
"")
        self.btn_refrescar.setObjectName("btn_refrescar")
        self.pages.addWidget(self.page_mostrar)
        self.horizontalLayout_3.addWidget(self.pages)
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.frame_inferior)
        TALLERUTC.setCentralWidget(self.centralwidget)

        self.retranslateUi(TALLERUTC)
        self.pages.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(TALLERUTC)

    def retranslateUi(self, TALLERUTC):
        _translate = QtCore.QCoreApplication.translate
        TALLERUTC.setWindowTitle(_translate("TALLERUTC", "MainWindow"))
        self.label_2.setText(_translate("TALLERUTC", "TALLER UTC"))
        self.label_6.setText(_translate("TALLERUTC", "Talleres UTC es un sistema \n"
" desarrollado por alumnos de la carrera de \n"
" Tecnologías de la información y comunicación \n"
" en el área de desarrollo de software  \n"
" como proyecto integrador"))
        self.label_5.setText(_translate("TALLERUTC", "ELIMINAR TALLER"))
        self.btn_taller_eliminar.setText(_translate("TALLERUTC", "ELIMIAR"))
        self.lbl_respuesta.setText(_translate("TALLERUTC", "RESPUESTA"))
        self.label_10.setText(_translate("TALLERUTC", "INGRESA EL NOMBRE DEL TALLER A ELIMINAR"))
        self.label_23.setText(_translate("TALLERUTC", "ALUMNOS"))
        item = self.tb_alumno.horizontalHeaderItem(0)
        item.setText(_translate("TALLERUTC", "ID"))
        item = self.tb_alumno.horizontalHeaderItem(1)
        item.setText(_translate("TALLERUTC", "NOMBRE"))
        item = self.tb_alumno.horizontalHeaderItem(2)
        item.setText(_translate("TALLERUTC", "CORREO"))
        item = self.tb_alumno.horizontalHeaderItem(3)
        item.setText(_translate("TALLERUTC", "TELEFONO"))
        self.btn_alumno_buscar.setText(_translate("TALLERUTC", "BUSCAR"))
        self.label_24.setText(_translate("TALLERUTC", "ID"))
        item = self.tb_alumno_taller.horizontalHeaderItem(0)
        item.setText(_translate("TALLERUTC", "TALLER INSCRITO"))
        item = self.tb_alumno_taller.horizontalHeaderItem(1)
        item.setText(_translate("TALLERUTC", "ALUMNO NOMBRE"))
        self.label_25.setText(_translate("TALLERUTC", "AGREGAR A TALLER:"))
        self.btn_alumno_buscar_2.setText(_translate("TALLERUTC", "REGISTRAR"))
        self.label_9.setText(_translate("TALLERUTC", "LOGIN"))
        self.btn_ingresar.setText(_translate("TALLERUTC", "INGRESAR"))
        self.btn_ir_registrar.setText(_translate("TALLERUTC", "REGISTRAR"))
        self.label_26.setText(_translate("TALLERUTC", "INGRESA TU USUARIO"))
        self.label_27.setText(_translate("TALLERUTC", "INGRESA TU CONTRASEÑA"))
        self.label_28.setText(_translate("TALLERUTC", "OLVIDÉ MI CONSTRASEÑA"))
        self.label_35.setText(_translate("TALLERUTC", "COMPU 1"))
        self.label_36.setText(_translate("TALLERUTC", "COMPU 3"))
        self.label_37.setText(_translate("TALLERUTC", "COMPU 2"))
        self.status1.setText(_translate("TALLERUTC", "STATUS"))
        self.status2.setText(_translate("TALLERUTC", "STATUS"))
        self.status3.setText(_translate("TALLERUTC", "STATUS"))
        self.btnOcupar1.setText(_translate("TALLERUTC", "OCUPAR"))
        self.btnOcupar2.setText(_translate("TALLERUTC", "OCUPAR"))
        self.btnOcupar3.setText(_translate("TALLERUTC", "OCUPAR"))
        self.btn_bebida.setText(_translate("TALLERUTC", "BEBIDAS"))
        self.btn_alimento.setText(_translate("TALLERUTC", "ALIMENTOS"))
        self.btn_postre.setText(_translate("TALLERUTC", "POSTRES"))
        self.label_30.setText(_translate("TALLERUTC", "ELIGE UNA OPCION"))
        self.label_31.setText(_translate("TALLERUTC", "BEBIDAS"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("TALLERUTC", "PRODUCTO1"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("TALLERUTC", "PRODUCTO2"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("TALLERUTC", "PRODUCTO3"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.label_32.setText(_translate("TALLERUTC", "ARCHIVOS"))
        self.label_33.setText(_translate("TALLERUTC", "subir archivo"))
        self.label_34.setText(_translate("TALLERUTC", "BUSCAR ARCHIVO:"))
        self.nombre_archivo.setText(_translate("TALLERUTC", "NOMBRE ARCHIVO"))
        self.nombre_archivo_abrir.setText(_translate("TALLERUTC", "NOMBRE ARCHIVO"))
        self.label_16.setText(_translate("TALLERUTC", "EDITAR TALLER"))
        self.label_17.setText(_translate("TALLERUTC", "INGRESA EL ID DEL TALLER A ELIMINAR"))
        self.btn_taller_editar.setText(_translate("TALLERUTC", "EDITAR"))
        self.label_18.setText(_translate("TALLERUTC", "ID"))
        self.btn_taller_buscar.setText(_translate("TALLERUTC", "BUSCAR"))
        self.label_19.setText(_translate("TALLERUTC", "NOMBRE"))
        self.label_20.setText(_translate("TALLERUTC", "DESCRIPCION"))
        self.label_21.setText(_translate("TALLERUTC", "INSTRUCTOR"))
        self.label_22.setText(_translate("TALLERUTC", "HORARIO"))
        self.label_4.setText(_translate("TALLERUTC", "AGREGAR TALLER"))
        self.label_11.setText(_translate("TALLERUTC", "INGRESA LOS DATOS DEL TALLER"))
        self.btn_guardar.setText(_translate("TALLERUTC", "GUARDAR"))
        self.label_12.setText(_translate("TALLERUTC", "NOMBRE"))
        self.label_13.setText(_translate("TALLERUTC", "DESCRIPCIÓN"))
        self.label_14.setText(_translate("TALLERUTC", "INSTRUCTOR"))
        self.label_15.setText(_translate("TALLERUTC", "HORARIO"))
        self.label_3.setText(_translate("TALLERUTC", "TALLERES UTC"))
        item = self.tb_taller.horizontalHeaderItem(0)
        item.setText(_translate("TALLERUTC", "ID"))
        item = self.tb_taller.horizontalHeaderItem(1)
        item.setText(_translate("TALLERUTC", "NOMBRE"))
        item = self.tb_taller.horizontalHeaderItem(2)
        item.setText(_translate("TALLERUTC", "DESCRIPCIÓN"))
        item = self.tb_taller.horizontalHeaderItem(3)
        item.setText(_translate("TALLERUTC", "TALLERISTA"))
        item = self.tb_taller.horizontalHeaderItem(4)
        item.setText(_translate("TALLERUTC", "HORARIO"))
        self.btn_refrescar.setText(_translate("TALLERUTC", "REFRESCAR"))
